bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 100
    default_server_timeout: 20
    
    default_nav_to_pose_bt_xml: "/home/user/akm_ws2/src/akm_navigation2/params/car_nav.xml"
    default_nav_through_poses_bt_xml: "/home/user/akm_ws2/src/akm_navigation2/params/car_nav.xml"
    
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node
      - nav2_is_battery_charging_condition_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    odom_topic: /odom
    use_sim_time: False
    controller_frequency: 5.0
    transform_tolerance: 2.0
    
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    
    progress_checker_plugin: "progress_checker"
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.10
      movement_time_allowance: 20.0
    
    goal_checker_plugins: ["general_goal_checker"] 
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      # 🔥 修改 1: 位置容忍度保持 0.30 (30cm)
      xy_goal_tolerance: 0.30
      # 🔥 修改 2: 角度容忍度收紧到 0.05 (约2.8度)，确保车头必须正
      yaw_goal_tolerance: 0.05
      stateful: True

    controller_plugins: ["FollowPath"]
    controller_plugin_types: ["nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      
      # 🔥 修改 3: 速度提升到 0.3 m/s
      desired_linear_vel: 0.3
      
      approach_velocity_scaling_dist: 1.0
      min_approach_linear_velocity: 0.15
      
      use_collision_detection: true
      
      max_allowed_time_to_collision_up_to_carrot: 5.0
      lookahead_dist: 2.5
      min_lookahead_dist: 1.5
      max_lookahead_dist: 4.0
      lookahead_time: 2.0
      use_rotate_to_heading: false
      allow_reversing: true
      max_angular_accel: 2.0
      max_robot_pose_search_dist: 10.0
      
      use_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 10.0
      regulated_linear_scaling_min_speed: 0.15
      
      use_cost_regulated_linear_velocity_scaling: true
      inflation_cost_scaling_factor: 2.0
      
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 0.5
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.05
      footprint: "[ [1.445, 0.575], [1.445, -0.575], [-0.405, -0.575], [-0.405, 0.575] ]"
      transform_tolerance: 2.0
      plugins: ["stvl_layer", "inflation_layer"]

      stvl_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        voxel_decay: 2.0
        decay_model: 0
        voxel_size: 0.05
        track_unknown_space: true
        mark_threshold: 0
        update_footprint_enabled: true
        combination_method: 1
        origin_z: 0.0
        z_resolution: 0.1
        z_voxels: 20
        publish_voxel_map: true
        transform_tolerance: 2.0
        observation_sources: front_livox rear_livox

        front_livox:
          data_type: PointCloud2
          topic: /livox/front/lidar
          sensor_frame: livox_frame_front
          marking: true
          clearing: true
          obstacle_range: 8.0
          min_obstacle_height: 0.2
          max_obstacle_height: 2.0
          inf_is_valid: true
          expected_update_rate: 0.0
          observation_persistence: 0.0
          vertical_fov_angle: 1.03
          horizontal_fov_angle: 6.28
          decay_acceleration: 5.0

        rear_livox:
          data_type: PointCloud2
          topic: /livox/rear/lidar
          sensor_frame: livox_frame_rear
          marking: true
          clearing: true
          obstacle_range: 8.0
          min_obstacle_height: 0.2
          max_obstacle_height: 2.0
          inf_is_valid: true
          expected_update_rate: 0.0
          observation_persistence: 0.0
          vertical_fov_angle: 1.03
          horizontal_fov_angle: 6.28
          decay_acceleration: 5.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 10.0
        inflation_radius: 0.55

global_costmap:
  global_costmap:
    ros__parameters:
      transform_tolerance: 2.0
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      footprint: "[ [1.445, 0.575], [1.445, -0.575], [-0.405, -0.575], [-0.405, 0.575] ]"
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        # 保持居中行驶的V型谷参数
        cost_scaling_factor: 2.0 
        inflation_radius: 0.55 
        
      always_send_full_costmap: True

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      downsample_costmap: false
      downsampling_factor: 1
      tolerance: 0.25
      allow_unknown: true
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      max_planning_time: 5.0
      motion_model_for_search: "REEDS_SHEPP"
      angle_quantization_bins: 72
      analytic_expansion_ratio: 3.5
      analytic_expansion_max_length: 5.0
      
      minimum_turning_radius: 3.2
      
      reverse_penalty: 1.2
      change_penalty: 40.0
      non_straight_penalty: 1.5
      cost_penalty: 5.0
      retrospective_penalty: 0.015
      lookup_table_size: 20.0
      cache_obstacle_heuristic: true
      
      smooth_path: True
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true

smoother_server:
  ros__parameters:
    use_sim_time: False
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["backup", "drive_on_heading", "assisted_teleop", "wait"]
    backup:
      plugin: "nav2_behaviors/BackUp"
      time_allowance: 20.0
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 2.0
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.5

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: False
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    
    max_accel: [3.0, 0.0, 3.0]
    max_decel: [-5.0, 0.0, -5.0]
    
    # 🔥 修改 4: 平滑器限速同步提升到 0.3
    max_velocity: [0.3, 0.0, 1.0]
    min_velocity: [-0.3, 0.0, -1.0]
    
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0