# 激光里程计+rpp
bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 100
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node
      - nav2_is_battery_charging_condition_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    odom_topic: /odom
    use_sim_time: False
    
    # 控制频率：大车建议低频，10Hz 足够，太快容易震荡
    controller_frequency: 10.0
    
    # 最小路径点数：防止路径太短导致报错
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    
    # 进度检查器：防止机器人卡住不动
    progress_checker_plugin: "progress_checker"
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    
    # 目标检查器：控制“到达终点”的判定
    goal_checker_plugins: ["general_goal_checker"] 
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25    # 到达终点容忍度 (0.25米)
      yaw_goal_tolerance: 0.25   # 角度容忍度
      stateful: True

    #以此加载 RPP 插件
    controller_plugins: ["FollowPath"]
    controller_plugin_types: ["nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"]

    # RPP 详细参数配置
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      
      # === 速度与安全距离 ===
      desired_linear_vel: 0.3        # 期望巡航速度 0.3 m/s
      max_allowed_time_to_collision_up_to_carrot: 3.5  # 0.3m/s * 3.5s ≈ 1.05米 (提前1米刹车)
      use_collision_detection: true  # 开启碰撞检测
      
      # === 预瞄距离 ===
      lookahead_dist: 2.0            # 预瞄 2.0 米
      min_lookahead_dist: 1.0        # 最小看 1.0 米
      max_lookahead_dist: 3.0        # 最远看 3.0 米
      lookahead_time: 2.0            # 动态调整
      
      # === 阿克曼底盘约束 ===
      use_rotate_to_heading: false   # 禁止原地旋转 (大车必备)
      allow_reversing: true         # 暂时禁止倒车 (先跑通前进)
      max_angular_accel: 1.0         # 限制角加速度，防止猛打方向
      max_robot_pose_search_dist: 10.0
      
      # === 弯道限速 ===
      use_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 3.0  # 转弯半径小于3米时减速
      regulated_linear_scaling_min_speed: 0.15  # 最慢减到 0.15 m/s
      
      # === 靠近障碍物限速 ===
      use_cost_regulated_linear_velocity_scaling: true
      inflation_cost_scaling_factor: 3.0        # 靠近障碍物时提前减速
      
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.05
      footprint: "[ [1.445, 0.575], [1.445, -0.575], [-0.405, -0.575], [-0.405, 0.575] ]"
      
      # 1. 启用插件：用 stvl_layer 替换原来的 voxel_layer
      plugins: ["stvl_layer", "inflation_layer"]

      # 7772. STVL 核心配置
      stvl_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        
        # === 核心魔法参数 ===
        voxel_decay: 0.5        # 寿命：障碍物如果没有新点刷新，2秒后自动消失（彻底解决人走不消的问题！）
        decay_model: 0          # 0=线性衰减 (推荐), 1=指数衰减
        voxel_size: 0.05        # 栅格分辨率 (5cm)，如果机器卡顿，可改大到 0.1
        track_unknown_space: true
        mark_threshold: 0       # 只要有1个点就标记障碍物
        update_footprint_enabled: true
        combination_method: 1   # 1=MAX (最保守)
        origin_z: 0.0
        z_resolution: 0.1
        z_voxels: 20            # 地图高度容量 2.0米
        publish_voxel_map: true # 在 RViz 里能看到彩色方块
        transform_tolerance: 0.5

        # === 双雷达输入源配置 ===
        observation_sources: front_livox rear_livox

        # --- 前雷达配置 ---
        front_livox:
          data_type: PointCloud2
          topic: /livox/front/lidar      # 前雷达话题
          sensor_frame: livox_frame_front # 必须正你的确！TF 坐标系
          marking: true
          clearing: true
          obstacle_range: 8.0            # 超过 8米 的不记为障碍
          min_obstacle_height: 0.1       # 滤除地面噪点 (0.1米以下算通畅)
          max_obstacle_height: 2.0       # 滤除天花板
          
          # STVL 视锥清除参数 (Livox Mid-360 专用)
          inf_is_valid: true             # 空数据也要利用
          expected_update_rate: 0.0      # 自动检测频率
          observation_persistence: 0.0
          vertical_fov_angle: 1.03       # 垂直视场角：Mid-360 约 59度 ≈ 1.03弧度
          horizontal_fov_angle: 6.28     # 水平视场角：360度 = 2π ≈ 6.28
          decay_acceleration: 5.0        # 移动物体消除加速因子 (人走得越快，消得越快)

        # --- 后雷达配置 ---
        rear_livox:
          data_type: PointCloud2
          topic: /livox/rear/lidar       # 后雷达话题
          sensor_frame: livox_frame_rear # 必须正确！
          marking: true
          clearing: true
          obstacle_range: 8.0
          min_obstacle_height: 0.1
          max_obstacle_height: 2.0
          
          inf_is_valid: true
          expected_update_rate: 0.0
          observation_persistence: 0.0
          vertical_fov_angle: 1.03
          horizontal_fov_angle: 6.28
          decay_acceleration: 5.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0
        inflation_radius: 0.55

global_costmap:  # 全局costmap (静态地图 + 远避障)
  global_costmap:
    ros__parameters:
      transform_tolerance: 1.0
      update_frequency: 1.0  # 更新频率 (Hz, 1低频)
      publish_frequency: 1.0  # 发布频率
      global_frame: map  # 全局帧 (map)
      robot_base_frame: base_link  # 机器人帧
      use_sim_time: False  # 仿真时间
      footprint: "[ [1.445, 0.575], [1.445, -0.575], [-0.405, -0.575], [-0.405, 0.575] ]"  # 足迹
      resolution: 0.05  # 分辨率
      track_unknown_space: true  # 跟踪未知空间
      plugins: ["static_layer", "inflation_layer"]  # 插件
      static_layer:  # 静态层 (/map订阅)
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:  # 膨胀
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0  # 缩放
        inflation_radius: 1.0  # 半径
      always_send_full_costmap: True

map_server:
  ros__parameters:
    use_sim_time: False
    # Overridden in launch by the "map" launch configuration or provided default value.
    # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid" # In Iron and older versions, "/" was used instead of "::"
      downsample_costmap: false           # whether or not to downsample the map
      downsampling_factor: 1              # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      tolerance: 0.25                     # dist-to-goal heuristic cost (distance) for valid tolerance endpoints if exact goal cannot be found.
      allow_unknown: true                 # allow traveling in unknown space
      max_iterations: 1000000             # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      max_on_approach_iterations: 1000    # Maximum number of iterations after within tolerances to continue to try to find exact solution
      max_planning_time: 5.0              # max time in s for planner to plan, smooth
      motion_model_for_search: "REEDS_SHEPP"    # Hybrid-A* Dubin, Redds-Shepp
      angle_quantization_bins: 72         # Number of angle bins for search
      analytic_expansion_ratio: 3.5       # The ratio to attempt analytic expansions during search for final approach.
      analytic_expansion_max_length: 3.0  # For Hybrid/Lattice nodes: The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting
      # analytic_expansion_max_cost: 200.0  # The maximum single cost for any part of an analytic expansion to contain and be valid, except when necessary on approach to goal
      # analytic_expansion_max_cost_override: false  #  Whether or not to override the maximum cost setting if within critical distance to goal (ie probably required)
      minimum_turning_radius: 4.0        # minimum turning radius in m of path / vehicle
      reverse_penalty: 2.0                # Penalty to apply if motion is reversing, must be => 1
      change_penalty: 0.0                 # Penalty to apply if motion is changing directions (L to R), must be >= 0
      non_straight_penalty: 1.2           # Penalty to apply if motion is non-straight, must be => 1
      cost_penalty: 2.0                   # Penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
      retrospective_penalty: 0.015
      lookup_table_size: 20.0             # Size of the dubin/reeds-sheep distance window to cache, in meters.
      cache_obstacle_heuristic: false     # Cache the obstacle map dynamic programming distance expansion heuristic between subsequent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
      # debug_visualizations: false         # For Hybrid nodes: Whether to publish expansions on the /expansions topic as an array of poses (the orientation has no meaning) and the path's footprints on the /planned_footprints topic. WARNING: heavy to compute and to display, for debug only as it degrades the performance.
      # use_quadratic_cost_penalty: False
      # downsample_obstacle_heuristic: True
      # allow_primitive_interpolation: False
      # coarse_search_resolution: 4         # Number of bins to skip when doing a coarse search for the path. Only used for all_direction goal heading mode.
      # goal_heading_mode: "DEFAULT"        # DEFAULT, BIDIRECTIONAL, ALL_DIRECTION
      smooth_path: True                   # If true, does a simple and quick smoothing post-processing to the path

      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true
        # refinement_num: 2
smoother_server:
  ros__parameters:
    use_sim_time: False
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.5
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: False
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    
    # 限制最大速度与 RPP 保持一致
    max_velocity: [0.3, 0.0, 0.5]
    min_velocity: [-0.3, 0.0, -0.5]
    
    # 限制加速度，让起步和刹车更柔和
    max_accel: [0.5, 0.0, 1.0]   # 线加速度 0.5 (温柔起步)
    max_decel: [-0.5, 0.0, -1.0] # 线减速度 -0.5 (温柔刹车)
    
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
